import Head from "next/head";
import Search from "../src/components/search/Search";
import Navbar from "../src/components/navbar/Navbar";
import Hero from "../src/components/hero/Hero";
import axios from "axios";
import React, { useEffect, useState } from "react";
import Result from "../src/components/result/Result";

export default function Home() {
  const [result, setResult] = useState([]);

  const makeApiCall = async (searchString) => {
    if(searchString.trim().length > 2){
      try {
      const res = await axios.get(
        `/api/omdbrequest?searchString=${searchString}`
      );
      if (res.status === 200) {
        setResult(res.data.result);
        console.log(res.data.result);
      }
    } catch (error) {
      console.log(error);
    }
    }else{
      setResult([]);
    }
    
  };
  useEffect(() => {
    setResult(result);
  }, [result]);
  return (
    <div>
      <Head>
        <title>Slick Media Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Project built by Paul Arokoola" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Search makeApiCall={makeApiCall} />
        <Result data={result} />
      </main>
    </div>
  );
}
